version: '3'

services:
  server:
    build: .
    ports: ['90:80']
  nginx:
    image: nginx:latest
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'